### ISSUE TITLE
spring boot 基于JWT实现单点登录 | Hexo

### ISSUE THREAD

**Issue by FleyX** [FleyX/technology-note#9]
http://www.tapme.top/blog/detail/2019-03-01-18-52/ 

 本篇原创发布于：FleyX 的个人博客 源码：github 照例配个图： 我叫林克，不是塞尔达  &emsp;&emsp;最近我们组要给负责的一个管理系统 A 集成另外一个系统 B，为了让用户使用更加便捷，避免多个系统重复登录，希望能够达到这样的效果——用户只需登录一次就能够在这两个系统中进行操作。很明显这就是单点登录(Single Sign-On)达到的效果,正好可以明目张胆的学一波单点登录知识

**Comment by Deng-chuan** [comment]
github的代码不全

**Comment by Deng-chuan** [comment]
后台代码做的事情不多，只需要实现下面的五个方法，然后下面只有四个方法，github里面只有三个方法，作者给弄全面些0.0

**Comment by FleyX** [comment]
文章中，应该是写错了，只有4个，代码中漏了一个，现在加上

**Comment by FleyX** [comment]
> @Deng-chuan
> 后台代码做的事情不多，只需要实现下面的五个方法，然后下面只有四个方法，github里面只有三个方法，作者给弄全面些0.0

已补全

**Comment by ZhangWangSHI** [comment]
你好，可以看一下你的系统A代码吗，

**Comment by FleyX** [comment]
> 你好，可以看一下你的系统A代码吗，

![image](https://user-images.githubusercontent.com/29558551/101357627-a953dd80-38d4-11eb-90b3-7abbd307d933.png)

**Comment by yuyaxiong6** [comment]
你好，请问账号的密码是多少？

**Comment by FleyX** [comment]
> 你好，请问账号的密码是多少？
账号密码相同即认证成功
![image](https://user-images.githubusercontent.com/29558551/136561818-21bd6078-c862-49e6-bc00-25922bd71aa6.png)

**Comment by yuyaxiong6** [comment]
你好：
&nbsp; 非常感谢回信!受宠若惊！
后台显示报错&nbsp;&nbsp;&nbsp;Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool



刚刚百度了在Windows本地安装了redis&nbsp; 还是有些许报错，能指导一下吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FleyX/technology-note"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FleyX/technology-note] spring boot 基于JWT实现单点登录 | Hexo (#9)





  
你好，请问账号的密码是多少？
 账号密码相同即认证成功
 
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FleyX** [comment]
> @yuyaxiong6
> 你好：
> &nbsp; 非常感谢回信!受宠若惊！
> 后台显示报错&nbsp;&nbsp;&nbsp;Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> 
> 
> 
> 刚刚百度了在Windows本地安装了redis&nbsp; 还是有些许报错，能指导一下吗？
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "FleyX/technology-note"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年10月8日(星期五) 晚上9:04
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [FleyX/technology-note] spring boot 基于JWT实现单点登录 | Hexo (#9)
> 
> 
> 
> 
> 
>   
> 你好，请问账号的密码是多少？
>  账号密码相同即认证成功
>  
>   
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

配置文件中修改redis的ip端口即可，另外本篇主要是讲单点登录实现思想，代码只是辅助说明，不能用于生产环境

**Comment by yuyaxiong6** [comment]
谢谢！




  
配置文件中修改redis的ip端口即可，另外本篇主要是讲单点登录实现思想，代码只是辅助说明，不能用于生产环境
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
